#!/bin/bash
useradd stalwart-jmap -s /sbin/nologin -M
mkdir -p /var/lib/stalwart-jmap
mkdir -p /etc/stalwart-jmap/certs
mkdir -p /etc/stalwart-jmap/private
chown stalwart-jmap:stalwart-jmap /var/lib/stalwart-jmap
